### ISSUE TITLE
Black graphical Artifacts

### ISSUE THREAD

**Issue by ddutchie** [haolange/Unity_ScreenSpaceLighting_Old#3]
Hello There. 

Thanks for this awesome project. Learning much from this. 

I had an issue today on a pc. 
It would render black squares whenever the camera with this stack is on is enabled. 

The Specs of the PC:
i7 5 series.
GTX 1080

It seems to happen in the tracing. 
Strange is that it works perfectly on my pc with the same GPU

**Comment by ddutchie** [comment]
![Spectator_1080p_20190712_12-35-46](https://user-images.githubusercontent.com/10877426/61122262-9485d700-a4a1-11e9-8cd3-9971921ebf23.png)

**Comment by ddutchie** [comment]
It happens when there are multiple cameras in the scene. It seems to sample the depth and velocity from the other cameras in the scene.

**Comment by haolange** [comment]
You need use DeferredRenderPath for BuiltIn RenderPipleine. and must enable PPS TemporalAA feature.

**Comment by ddutchie** [comment]
I don't have PPS in my project because of some other custom post effects, but I fixed this by making sure no other cameras are enabled when SSTS Camera is rendering. 

Thanks!

I have been trying to get this to work in VR, getting close. When I have some time I will try fix and do a pull request.

**Comment by haolange** [comment]
i will rebuild this effect in pps framework can support vr and multi camera.
