### ISSUE TITLE
error

### ISSUE THREAD

**Issue by laurentopia** [haolange/Unity_ScreenSpaceLighting_Old#4]
I'm getting this in 2019.3f5 
A multisampled texture being bound to a non-multisampled sampler. Disabling in order to avoid undefined behavior. Please use Texture2DMS in the shader.
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

PS:it looks gorgeous

**Comment by AleksandrSergeyevich** [comment]
Hello, did you manage to fix this?

**Comment by laurentopia** [comment]
no but it works kinda

**Comment by AleksandrSergeyevich** [comment]
yes it works, but the error crashes through time

**Comment by laurentopia** [comment]
good to know, I started using HDRP global illum
